# Generated by Django 3.2.9 on 2021-11-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='image',
            field=models.ImageField(default='/Users/bnorman/fashion/fashion_backend/media/images/default.png', upload_to='images/'),
        ),
    ]
