# Generated by Django 3.2.9 on 2021-11-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_cloth_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
