# Generated by Django 3.2.9 on 2021-11-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_cloth_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.TextField(),
        ),
    ]
